# Generated by Django 5.2.5 on 2025-08-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('webhook_secret', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_accounts', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_txn_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'created_at'], name='payments_pa_school__c20349_idx'), models.Index(fields=['provider', 'external_txn_id'], name='payments_pa_provide_e6d18b_idx')],
                'unique_together': {('provider', 'external_txn_id')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregator_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.aggregatoraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_id'], name='payments_we_provide_139ee0_idx')],
                'unique_together': {('event_id', 'aggregator_account')},
            },
        ),
    ]
