# Generated by Django 5.2.5 on 2025-08-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatoraccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='updated_at',
        ),
    ]
