# Generated by Django 5.2.5 on 2025-08-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_aggregatoraccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qbo_txn_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qbo_txn_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
