# Generated by Django 5.2.5 on 2025-08-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_qbo_txn_id_payment_qbo_txn_type'),
        ('schools', '0002_schooldirectoryconnection_student_studentidmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_student_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='qbo_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qbo_invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='school_student_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='schools.student'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'school_student_id'], name='payments_pa_school__dd010a_idx'),
        ),
    ]
