# Generated by Django 5.2.5 on 2025-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_provider_student_id_payment_qbo_customer_id_and_more'),
        ('schools', '0003_remove_schooldirectoryconnection_student_by_provider_path_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_school__dd010a_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_student_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'provider_student_id'], name='payments_pa_school__8b7fac_idx'),
        ),
    ]
