# Generated by Django 5.2.5 on 2025-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_payments_pa_school__dd010a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='narration',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
