version: "3.9"
services:
  web:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db, redis]
  worker:
    build: .
    command: celery -A config.celery worker -l info
    env_file: .env
    depends_on: [db, redis]
  beat:
    build: .
    command: celery -A config.celery beat -l info
    env_file: .env
    depends_on: [db, redis]
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: school_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
