# Generated by Django 5.2.5 on 2025-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schooldirectoryconnection_student_studentidmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldirectoryconnection',
            name='student_by_provider_path',
        ),
        migrations.RemoveField(
            model_name='schooldirectoryconnection',
            name='student_by_school_id_path',
        ),
        migrations.AlterUniqueTogether(
            name='studentidmap',
            unique_together={('school', 'provider_student_id')},
        ),
        migrations.AddField(
            model_name='schooldirectoryconnection',
            name='student_by_provider_id_path',
            field=models.CharField(default='/students/by-provider-id/{provider_student_id}', max_length=200),
        ),
        migrations.RemoveField(
            model_name='studentidmap',
            name='provider',
        ),
    ]
