# Generated by Django 5.2.5 on 2025-08-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_schooldirectoryconnection_student_by_provider_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBOConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(max_length=32)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('company_currency', models.CharField(default='USD', max_length=3)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qbo', to='schools.school')),
            ],
        ),
    ]
