apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-ingress.yaml
  - celery-worker-deployment.yaml
  - celery-beat-deployment.yaml

images:
  - name: school-payments
    newName: 594715259457.dkr.ecr.eu-west-1.amazonaws.com/school-payments
    newTag: v2025.09.22-0e18e2a0