apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - web-deployment.yaml
  - web-service.yaml
  - celery-worker-deployment.yaml
  - celery-beat-deployment.yaml

images:
  - name: school-payments
    newTag: latest