apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-payments-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school-payments-web
  template:
    metadata:
      labels:
        app: school-payments-web
    spec:
      containers:
      - name: web
        image: school-payments:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: school-payments-config
        - secretRef:
            name: school-payments-secret
        env:
        - name: PORT
          value: "8000"
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5