apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/configmap.yaml
  - ../../base/secret.yaml
  - ../../base/web-deployment.yaml
  - ../../base/web-service.yaml
  - ../../base/celery-worker-deployment.yaml
  - ../../base/celery-beat-deployment.yaml

patchesStrategicMerge:
  - replicas.yaml

namespace: school-payments-dev

images:
  - name: school-payments
    newTag: dev-latest