apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml

namespace: school-payments-dev

images:
  - name: school-payments
    newTag: dev-latest