apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - config-patch.yaml

namespace: school-payments-staging

images:
  - name: school-payments
    newTag: staging-latest