apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: config-patch.yaml
    target:
      kind: ConfigMap
      name: school-payments-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: school-payments-web

namespace: school-payments-staging

images:
  - name: school-payments
    newName: 594715259457.dkr.ecr.eu-west-1.amazonaws.com/school-payments
    newTag: v2025.09.23-acbb8713-pg